services:
  - type: web
    name: qmp-siemens-produktcheck
    env: node
    plan: starter
    buildCommand: npm install && npm run install-browsers
    startCommand: node server.js
    envVars:
      - key: SCRAPE_CONCURRENCY
        value: "4"
      - key: NODE_VERSION
        value: "18"
      - key: DISABLE_PLAYWRIGHT
        value: "0"